### ISSUE TITLE
make agreement to the framework

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#1]

**Comment by PatriciaHeimfarth** [comment]
Hi,
also ich hatte ja Xamarin vorgeschlagen, weil man damit Android und iOS gleichzeitig bedienen könnte. 
Dann gibt es noch Flutter, damit kann man das auch.
Oder halt jeweils eine native App für Android und iOS, das wäre dann aber mehr Arbeit. Was meinst du?

**Comment by chnuessli** [comment]
Ich bin einverstanden mit Xamarin, wenn du das gerne machen würdest. Ich bin einfach mit .NET usw. nicht vertraut. Würdest du da den Löwenanteil übernehmen? Oder sollen wir noch andere Mitwirkende suchen?

**Comment by chnuessli** [comment]
Die Frage des Hosting müssten wir dann noch klären

**Comment by PatriciaHeimfarth** [comment]
Ich würde sagen, wir fangen einfach an und schauen dann, was sich ergibt.
Willst du dann vielleicht festhalten, was grob gemacht werden soll? Dann können wir es Schritt für Schritt realisieren

**Comment by chnuessli** [comment]
Hallo @PatriciaHeimfarth 
Ja, werde dieses Wochenende die Schritte und Spezifikation mal fertig stellen.

**Comment by chnuessli** [comment]
Hallo @PatriciaHeimfarth 
Ja, ich werde dieses Wochenende die Schritte und Spezifikation mal fertig stellen.

**Comment by chnuessli** [comment]
Die requirements.md ist nun aktualisiert, mal auf Englisch für weitere Contributors.

**Comment by chnuessli** [comment]
Hallo @PatriciaHeimfarth ein weiterer User würde uns unterstützen. Wäre Flutter auch eine Option für dich?
@elektrolytenmangel würde sich da auch bereits etwas auskennen.

**Comment by elektrolytmangel** [comment]
Ich denke es wäre sinvoll, zuerst zu Überprüfen welche Kartenframeworks zur Verfügung stehen und in Frage kommen. Für Andorid und iOS gibt es jeweils ein MapBox SDK das OpenSource ist. Was es sonst noch gibt ist etwas durchmischt, soweit ich das gesehen habe: https://wiki.openstreetmap.org/wiki/Frameworks#Displaying_interactive_maps 
@PatriciaHeimfarth hast du dazu bereits eine Idee?

**Comment by elektrolytmangel** [comment]
Nach einiger Recherche zu Multi-Plattform-Frameworks habe ich folgendes gefunden: 
- Xamarin: jedoch schlechte Unterstützung für Custom Karten
- Unity: trotz Mapbox SDK wahrscheinlich etwas kompliziert für das aktuelle Projekt
- Ionic/Cordova: alle Vorteile der Webentwicklung, dafür ewas schlechtere Performance und nicht natives UI
- React Native: alle Vorteile der Webentwicklung, hervorragende Performance, UI wie native möglich

Habe ich etwas vergessen?
Ich würde aufgrund der oben gennanten Punkte eigentlich React Native vorschlagen.

Bitte um Ergänzung oder Anmerkung!

**Comment by chnuessli** [comment]
Hallo @elektrolytmangel 
Ich denke wir sollten React Native eine Chance geben und es damit versuchen. Vielleicht kann @PatriciaHeimfarth auch so etwas profitieren und mitmachen? Ich bin gerade React.js etwas am anschauen, sieht vielversprechend aus. React Native wird zwar gerade sehr gehyped, aber sieht solide aus.

**Comment by havogt** [comment]
Hi!
Ich könnte mir vorstellen auch etwas zur app beizutragen. Als ich die defikarte zum ersten mal gesehen hab (twitter vermutlich), hab ich gedacht, sie verdient eine app...
Ich bin jedoch etwas flutter fixiert, weil App/Web Entwicklung nur ein Hobby ist und ich mein bischen Freizeit nicht in noch ein weiteres Framework investieren will. Was ich unter anderem beitragen könnte wäre ein CI/CD setup via GitHub actions inklusive automatisches Deployment in Apple TestFlight und Google Play Store test channels. Habe mir vorhin auch kurz ein map package (https://pub.dev/packages/flutter_map) angeschaut. Sieht für mich so aus als würde man damit relative schnell die Grundfunktionalität hinbekommen sollte.
Allerdings will ich jetzt die Entscheidung auch nicht zu sehr beeinflussen, weil ich nicht garantieren kann, wieviel ich beitragen kann...
Grüsse Hannes

**Comment by chnuessli** [comment]
Hallo @havogt vielen Dank für dein Interesse.
Die Entscheidung für ein Framework ist keine Einfache. Da @elektrolytmangel aber laut eminen Infos bereits etwas angefangen hat wäre es doof zu wechseln. Ich denke aber, mit den CI/CD Setups könntest du uns sicher untersützen. Vielleicht packt es dich ja trotzdem noch, bei React Native mitzuhelfen. Wir müssen zuerst ausmerzen, was wir alles benötigen.

Gruss Christian

**Comment by havogt** [comment]
Klar, kann ich verstehen. Falls ihr euch doch noch für Flutter entscheidet, lasst es mich wissen! ;)

**Comment by chnuessli** [comment]
Ich denke wir können das hier schliessen. Die App wurde auf React Native aufgebaut. Danke allen für die Diskussion.
