### ISSUE TITLE
Layer switch isn't working when in "add defi" mode

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#103]
the leayer switch isn't working when adding a defi.

**Comment by elektrolytmangel** [comment]
Works for me, but problem is, that on iOS the zoom level can be higher than 19, where no OSM tiles are available anymore.![image](https://user-images.githubusercontent.com/54470310/109414755-e18b2980-79b4-11eb-917f-11c3a8a49164.png)

**Comment by elektrolytmangel** [comment]
@chnuessli can you please verify this? Then we can close the bug or create a feature request from it.

**Comment by chnuessli** [comment]
yes it's the zoom level. maybe it changes if we got more layers. for now, not mentionable. closing.
