### ISSUE TITLE
Change the phoneNumberPattern to more forgiving pattern

### ISSUE THREAD

**Issue by johannrichard** [chnuessli/defikarte.ch-app#106]
The current `phoneNumberPattern` is quite unforgiving with different ways of writing a number. E.g. with the current pattern, only the first three of the following examples will be valid numbers (See https://regex101.com/r/2q0OR5/1) :

```
+41000000000
0000000000
000 000 0000
000 000 00 00
0041 00 0000000
+41 00 000 00 00 
```

(Funny enough the pattern displayed in the app as a hint (`+41 79 000 00 00`) is not a valid number with the current pattern)

https://github.com/chnuessli/defikarte.ch-app/blob/12662ffe88de5e114b38a939df5dfd8ddf3c4fb8/backend/DefikarteBackend/DefikarteBackend/Validation/DefibrillatorRequestValidator.cs#L8

Here's an alternative suggestion which will match all of the above numbers and still ensures valid numbers (See https://regex101.com/r/c2oM3K/2)

`^(\+41|0041|0)\s?(\d{2})\s?(\d{3})\s?(\d{2})\s?(\d{2})$`

**Comment by chnuessli** [comment]
Thank you for reporting this. We will look into it.

**Comment by chnuessli** [comment]
PS: if you want, feel free to leave your PR and help to make the app better. Kind regards

**Comment by johannrichard** [comment]
I'll prepare a PR (though I can't probably test it myself - but if that's OK it'll happily prepare one)

**Comment by elektrolytmangel** [comment]
If you want, we can setup a call or something. Testing should not be that hard if you are capable of setting up an node js env and wanted to.

**Comment by johannrichard** [comment]
> If you want, we can setup a call or something. Testing should not be that hard if you are capable of setting up an node js env and wanted to. 

I'll see what I can do. Setting up the dev environment should in principle be doable. :see_no_evil: It's more about the tool chain for the Azure Functions that I have to setup and (YAIDE - Yet - Another IDE) that I'm a bit worried about for just a small change. :-)

**Comment by elektrolytmangel** [comment]
I forgot about the backend. For sure I will do the testing for you, after you creates the pull request :)

**Comment by chnuessli** [comment]
hello @johannrichard can you proof the mentioned PR if this is in your sense? Then we can close this issue. Thanks for your feedback

**Comment by johannrichard** [comment]
Looks good to me, apologies for not having prepared it myself - got swamped with (other) work. 🙈 Thanks for picking it up.

**Comment by chnuessli** [comment]
No worries, thanks for the feedback and the input, very appreciated. Solving the issue now. Thx @elektrolytmangel
