### ISSUE TITLE
OSM Layer on Android not working

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#107]
The map layer on Android isn't working. When i toggle the button, the map layer doesn't change

**Comment by elektrolytmangel** [comment]
I found this. We have then probably to use another tile-provider. @chnuessli do you have one in place?

**Comment by chnuessli** [comment]
Why? Is it a problem with the tile provider? Because in iOS it's working.

**Comment by elektrolytmangel** [comment]
This seems to be fixed. I close the issue.
