### ISSUE TITLE
Auto-locate by launching the app

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#108]
It' would be nice of the app will auto-locate the user and show the next defis directly at the start of the app.

**Comment by elektrolytmangel** [comment]
The feature is added for iOS and Android. After the app gained focus, it is tried to get the location (as before), and after the first valid coordinates are there, it is zoomed to it.

**Comment by elektrolytmangel** [comment]
Is on iOS in production, in android soon as well. I close the issue.
