### ISSUE TITLE
make router use system "map" apps

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#11]
e.g google maps or apple maps

**Comment by elektrolytmangel** [comment]
This feature is also somehow implemented. It opens the apple maps app on iOS, on android it opens the default maps app. But the navigation parameters (to set start- and end-points) works only with google maps and apple maps.
The button is available on the ListScreen.

**Comment by elektrolytmangel** [comment]
Google maps does not work. Habe to fix this later.

**Comment by elektrolytmangel** [comment]
Fixed google maps.
