### ISSUE TITLE
Improve the way, how a defi is located by adding it

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#134]
We have several reports for defis that are mapped incorrectly. All those mappings are done by the app and often "midfield".
We need to improve the way, or at least, show the location in an approval screen.

Otherwise we need to confirm the location as an admin, which will be a lot of work

**Comment by elektrolytmangel** [comment]
I added a possible solution on android and ios with system dialogs, and as well moving the marker when out of map-region (not visible).

**Comment by elektrolytmangel** [comment]
Solution is on iOS in production, and android soon as well. I close the issue.
