### ISSUE TITLE
create deployment process to app stores

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#14]
we need to set up a deployment process to push to the app stores.

**Comment by chnuessli** [comment]
Maybe you @havogt have some experience in that process?

**Comment by chnuessli** [comment]
Developer Accounts to be ordered tommorrow

**Comment by chnuessli** [comment]
both accounts ordered today.

**Comment by elektrolytmangel** [comment]
We need Secrets: 
* EXPO_CLI_USERNAME
* EXPO_CLI_PASSWORD
* EXPO_APPLE_ID
* EXPO_APPLE_PASSWORD
* EXPO_APP_SPECIFIC_PASSWORD
* PHONE_NUMBER
* <Path to Google Sevice Account Json> (whatever that means) probably also as secret
* GOOGLE_MAPS_API (I will deliver you this key as soon as possible, till then use the one from the app.json)
@chnuessli  can you add this? You have to create a google service account: https://developers.google.com/android/management/service-account

**Comment by chnuessli** [comment]
@elektrolytmangel a secret for every line?

**Comment by elektrolytmangel** [comment]
Yes. Probably for the expo, you can take the bot-user I created (I sent you the token on another channel). If the bot user does not work, you can insert yours.

**Comment by chnuessli** [comment]
EXPO_CLI_USERNAME
EXPO_CLI_PASSWORD
EXPO_APPLE_ID
EXPO_APPLE_PASSWORD
EXPO_APP_SPECIFIC_PASSWORD
PHONE_NUMBER


Secrets added

**Comment by chnuessli** [comment]
all secrets added

**Comment by elektrolytmangel** [comment]
as it works now, at least publishing the JS part, I will close this issue. If more automatic stuff is needed, create a new issue.
