### ISSUE TITLE
Defis added with wrong location

### ISSUE THREAD

**Issue by habi** [chnuessli/defikarte.ch-app#158]
I've found a cluster of defibrillators with the same, wrong coordinates: https://osm.li/QGR

I'm wondering how these five defibrillators ended up at the same, wrong place.

**Comment by chnuessli** [comment]
Schauen wir uns an, danke!

**Comment by das-g** [comment]
<details><summary>result of the overpass query (click to expand)</summary>

```json
{
  "version": 0.6,
  "generator": "Overpass API 0.7.59.1 2a9d9642",
  "osm3s": {
    "timestamp_osm_base": "84464",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL."
  },
  "elements": [

{
  "type": "node",
  "id": 8563003017,
  "lat": 46.9399504,
  "lon": 7.4000000,
  "tags": {
    "access": "yes",
    "defibrillator:location": "im 24-Stundenbereich (bei Bancomat)",
    "emergency": "defibrillator",
    "emergency:phone": "144",
    "indoor": "yes",
    "opening_hours": "24/7",
    "operator": "Raiffeisenbank Merenschwand"
  }
},
{
  "type": "node",
  "id": 8564112918,
  "lat": 46.9399504,
  "lon": 7.4000000,
  "tags": {
    "access": "no",
    "defibrillator:location": "Bauarena Empfang",
    "description": "während er Öffnungszeiten",
    "emergency": "defibrillator",
    "emergency:phone": "144",
    "indoor": "yes",
    "opening_hours": "Mo-Fr 09:00 - 18:00; Sa 09:00 - 16:00",
    "phone": "+41 44 908 55 77"
  }
},
{
  "type": "node",
  "id": 8571838626,
  "lat": 46.9399504,
  "lon": 7.4000000,
  "tags": {
    "access": "yes",
    "defibrillator:location": "Turnhalle 5736 Burg",
    "description": "Bei der Schuhwaschanlage",
    "emergency": "defibrillator",
    "emergency:phone": "144",
    "indoor": "no",
    "opening_hours": "24/7"
  }
},
{
  "type": "node",
  "id": 9028654618,
  "lat": 46.9399504,
  "lon": 7.4000000,
  "tags": {
    "access": "yes",
    "defibrillator:location": "Forchstrasse 84",
    "emergency": "defibrillator",
    "emergency:phone": "144",
    "indoor": "yes",
    "opening_hours": "Mo- Fr 08:00-18:00",
    "operator": "Firma",
    "phone": "0434883838"
  }
},
{
  "type": "node",
  "id": 9076026127,
  "lat": 46.9399504,
  "lon": 7.4000000,
  "tags": {
    "access": "yes",
    "defibrillator:location": "Plegeheim St.Otmar",
    "description": "während 7:00-19:00 Verfügbar",
    "emergency": "defibrillator",
    "emergency:phone": "144",
    "indoor": "yes",
    "operator": "Pflegeheim St.Otmar",
    "phone": "0712744711"
  }
}

  ]
}
```

</details>

So it's 6 defibrillators allegedly all at `"lat": 46.9399504`, `"lon": 7.4000000`, a suspiciously "round" longitude.

**Comment by chnuessli** [comment]
> I've found a cluster of defibrillators with the same, wrong coordinates: https://osm.li/QGR
> 
> I'm wondering how these five defibrillators ended up at the same, wrong place.

This was an error in the early versions of the app. In the latest release the user is actively asked to proof the location of the defi. this error shouldn't be triggered anymore.

**Comment by chnuessli** [comment]
> 

Hello @das-g 
Do you have the source of your overpass request? I'm interested in this, maybe it helps to identify more clusters?

**Comment by habi** [comment]
That was my query, specifically geared 'manually' to look a little bit `around` the location where I found this defi-cluster by chance.

**Comment by das-g** [comment]
If by "source" you mean the query source code, that's
```
[out:json][timeout:25];
{{radius=25}}
(
  node["emergency"="defibrillator"](around:{{radius}},{{geocodeCoords:Freiburgstrasse 249b}}); 
);
out body;
>;
out skel qt;
```
as can be seen on https://osm.li/QGR

**Comment by habi** [comment]
Here's one more: https://www.openstreetmap.org/node/8717762117/ (also with non-internationalized phone number).
According to the `defibrillator:location` in St. Gallen, but mapped in Bümpliz, close to where the initially reported bunch were...

**Comment by chnuessli** [comment]
Hello @habi 
I change this defi... this was over a year ago. From then, several changes should prevent this.

**Comment by habi** [comment]
Just for reference:
- https://www.openstreetmap.org/node/8449233017/history was also added at a completely wrong place (and 'survived' two QA sessions there).

**Comment by habi** [comment]
https://www.openstreetmap.org/node/8850708318/ is also completely wrong. I'm currently trying to find out where to place it correctly.
