### ISSUE TITLE
Add `phone` in international format

### ISSUE THREAD

**Issue by habi** [chnuessli/defikarte.ch-app#159]
The `phone` key of a <del>POI</del>defibrillator [should added in international format](https://wiki.openstreetmap.org/wiki/Key:phone#Usage).

While correcting some wrong values [^1] in my vicinity I'm seeing a *lot* of defibrillator which don't use the international format.
Would it be possible to add this to the phone number automatically?

[^1]: and stumbling over a bunch of defibrillators in the wrong place: https://github.com/chnuessli/defikarte.ch-app/issues/158

**Comment by chnuessli** [comment]
This was deployed, long time ago :) sorry, never closed the issue.
