### ISSUE TITLE
Form fields and validation

### ISSUE THREAD

**Issue by elektrolytmangel** [chnuessli/defikarte.ch-app#20]
Validate all fields in the app it self, also add the validation to the api. 
@chnuessli can you write down which fields should be supported and which rules should be applied to them (i.e. required, some regex, length, datatype)?

**Comment by chnuessli** [comment]
yes, i will do it, just give me some time for that :)

**Comment by chnuessli** [comment]
added comments for the required fields and validation data (opening_hours)
insert description
opening_hours tool validator link is in comments

**Comment by chnuessli** [comment]
@chnuessli look for a good validator api tommorrow

**Comment by elektrolytmangel** [comment]
Yes this should work, thanks.

**Comment by chnuessli** [comment]
@elektrolytmangel whats the best programming language for implementing an opening_hours validation? Or should that work too with your latest commit?

**Comment by elektrolytmangel** [comment]
For the app we could use the node js / javascript module you mentioned. For the backend, I did not checked it, but there is also a solution. At least a regex could handle most of the cases (language independent).

**Comment by elektrolytmangel** [comment]
Backend validation is still missing. This is next up.

**Comment by elektrolytmangel** [comment]
Added validation for all fields in the app, added validation in backend exept for opening_hours (do not know how to solve this right now), fixed input behavior
