### ISSUE TITLE
Icons for iOS and Android

### ISSUE THREAD

**Issue by elektrolytmangel** [chnuessli/defikarte.ch-app#30]
To deploy the app to play and app store, we need some icons. The icon guidline from expo says it should have an icon of 1024x1024, expo then generates the other icons by itself. For android there is at least a 512x512 icon needed (can be the same as the one for iOS).
@chnuessli can you please prepare the needed icon?
Expo doc: https://docs.expo.io/guides/app-icons/

**Comment by chnuessli** [comment]
407dcb908cc396fccda2d13b1da824dd75dfdcc0

all icons set in app/defikarte/assets/icons
