### ISSUE TITLE
bottom menu must be higher

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#32]
On iOS and the new iphones the menu bar is too low. the user has to point very good to the menu

**Comment by elektrolytmangel** [comment]
Please verify if the size is better now, I made it to fit to 8% of the screen (seems good on iOS 4.7" and Android 5.2")

**Comment by elektrolytmangel** [comment]
@chnuessli Please test this on an iPhone with notches and rounded corners

**Comment by chnuessli** [comment]
Works for me, we can co a bit higher to the notch

**Comment by elektrolytmangel** [comment]
probably we check this out together...

**Comment by elektrolytmangel** [comment]
Fixed the insets of top status bar and also the bottom stuff in iOS and also android (if any)
