### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#34]
Issue for all the user feedback.

**Comment by pvoser** [comment]
@chnuessli definarte.ch oder Definarte.ch?
AppName ist nicht gleich dem Logo ( Gross- Kleinschreibung)
![5C352505-C9CC-4F68-A92D-3A6C05575453](https://user-images.githubusercontent.com/10988706/105623499-716c0f80-5e1a-11eb-94d1-756b457c0c42.jpeg)

**Comment by pvoser** [comment]
@chnuessli UI auf iPhone Xs
Auf der hellen Karte sind die System-Informationen (Uhrzeit, Empfang, Batterie, usw.) kaum zu erkennen. Diese sollten dann auf schwarz wechseln.

![83176753-3069-4796-A533-014D74EF9CD2](https://user-images.githubusercontent.com/10988706/105623571-08d16280-5e1b-11eb-86df-8cd1b6824f8c.jpeg)


Button-Leiste zu tief auf iOS.

**Comment by pvoser** [comment]
@chnuessli Neuen Standort erfassen. „Anleitungs-Text“ zu hoch und überdeck die System-Informationen (Uhrzeit, Empfang, Batterie, zurück zur vorherigen App, usw.):

![F366E563-E462-432B-8A10-75462D0DB582](https://user-images.githubusercontent.com/10988706/105623668-ac227780-5e1b-11eb-80aa-4448612c36a4.jpeg)

**Comment by pvoser** [comment]
@chnuessli Neuen Standort erfassen - Informationen:
Die IU Elemente für Copy, Paste, Select sind alle in englisch, trotz deutschen Spracheinstellungen.

![0090715A-F2EE-4D34-9DBE-082FFFA6741E](https://user-images.githubusercontent.com/10988706/105623800-ed675700-5e1c-11eb-87aa-61d0a216bbb5.png)

**Comment by pvoser** [comment]
@chnuessli Neuer Standort erfassen- Feld Beschreibung:

Evtl. Umbrechen, wenn eine lange Beschreibung eingegeben wird:

![B431C204-0FE3-4B58-95A8-2082426612B9](https://user-images.githubusercontent.com/10988706/105623870-741c3400-5e1d-11eb-9d6c-626ff825dfaf.png)

**Comment by pvoser** [comment]
@chnuessli Neuen standort erfassen - Telefonnummer:

Die Tastatur überdeck ein wenig das Eingabefeld der Telefonnummer:
![F5A20A09-80AE-4CB5-8507-21C0AD5949B5](https://user-images.githubusercontent.com/10988706/105623901-b8a7cf80-5e1d-11eb-95df-f0fe41a65eae.jpeg)

**Comment by pvoser** [comment]
@chnuessli war alles iOS, App Version 1.0.0

**Comment by chnuessli** [comment]
hey @pvoser herzlichen Dank für dein Feedback. Ich habe wo nötig Issues erfasst, einiges ist bereits erledigt oder schon bekannt. Zu unserer Nachvollziehbarkeit liste ich diese hier kurz auf.

- Unteres Menü zu tief: Ist in #32 und einem neuen Build bereits gelöst.
- Das Problem mit der Anzeige des Systemtextes habe ich in #37 erfasst. Tritt bei mir zwar nicht auf..
- Namensänderung des Builds zu Defikarte.ch in #33 
- Umbruch bei langen Eingaben: #38
- Pop up neuer Defi in #39
- Copy Paste in Systemtext #40
- ui verbesserung bei telefonnummer eingabe #41

**Comment by pvoser** [comment]
@chnuessli Name der App ist defikarte-app:
![A82FE956-3CBF-4772-8297-1EFD34FC0FC0](https://user-images.githubusercontent.com/10988706/105752162-37e4f280-5f47-11eb-8420-840f9049b128.jpeg)

Evtl. umbenennen nach defikarte.ch?

iOS, iPhone Xs, Darkmode 😉

**Comment by pvoser** [comment]
@chnuessli Infos zu Defi - Übersetzung
Zugang wird mit „yes“ oder „no“ angezeigt:

![05163864-B484-454B-BE2C-7B3A48EA5D14](https://user-images.githubusercontent.com/10988706/105753614-46cca480-5f49-11eb-8054-5d49da0f2d09.jpeg)

Schöner wäre: Ja / Nein

**Comment by pvoser** [comment]
@chnuessli Zoom mit einem Finger

Wenn man ein Defi-Symbol antippt und dann loslässt und gleich nochmal nebendran tippt und hält (alles mit einem Finger), dann kann man plötzlich mit einem Finger die Karte zoomen.

Video ist wohl zu gross. Ich schicke es dem @elektrolytmangel  😊

**Comment by pvoser** [comment]
Ok, das mit dem Zoomen mit einem Finger ist ein Feature, dass ich nicht kannte 😄. @chnuessli kannst du ignorieren mein Meldung 😊

**Comment by pvoser** [comment]
@chnuessli Detailmarker wird 2mal geladen, wenn nahe am Bildschirmrand

Tippt man auf ein Icon, dass nahe am Bildschirmrand ist, so wird der Detailmarker 2mal geladen. Resp. Er öffnet sich, schliesst sich und wird wieder geöffnet.

Video geht an @elektrolytmangel

**Comment by pvoser** [comment]
@chnuessli Notrufnummer auf Detailmarker 

Die Notrufnummer auf dem Detailmarker als Telefonlink hinterlegen. Wäre evtl. auch was für die Listenansicht?

**Comment by elektrolytmangel** [comment]
Feddback from @chrootlogin:
Same as already in issue #32 
Request for new feature: Emergency-Button to call 112 / 144 and show the common questions they ask, so you can already prepare.

**Comment by chnuessli** [comment]
> Emergency-Button to call 112 / 144 and show the common questions they ask, so you can already prepare.

The call button is a good idea, but the questions are different in every region.. because the emergency dispatch services have different asking schemas and products

**Comment by chnuessli** [comment]
> @chnuessli Notrufnummer auf Detailmarker
> 
> Die Notrufnummer auf dem Detailmarker als Telefonlink hinterlegen. Wäre evtl. auch was für die Listenansicht?

Erledigt

**Comment by pvoser** [comment]
Nice! OSM MapLayer 👍🏻

It woul be nice if the OSM MapLayer button change the color if the OSM Layer is active:
![3A591683-3AF7-4A72-905A-C45BFBFC07F9](https://user-images.githubusercontent.com/10988706/107887176-75182100-6f04-11eb-8b2d-202465806d1c.jpeg)

**Comment by elektrolytmangel** [comment]
@pvoser I will add this in #83

**Comment by chnuessli** [comment]
all user feedback from beta testing solved or in an own issue. feedback from live users are also created as an issue. closing this. THANKS to all the BETA Tester
