### ISSUE TITLE
change the the system default text to dark when in dark mode

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#37]
change the colors to black if the light map is selected, otherwise the system informations are unreadable.

**Comment by pvoser** [comment]
@chnuessli Mein iOS ist auf das dunkle Design eingestellt. Evtl. liegt es an dem.

**Comment by chnuessli** [comment]
@pvoser yes, it's on th eios dark mode, i changed the issue

**Comment by elektrolytmangel** [comment]
Always set the status bar to 'dark-content' and for android use background color 'transparent'
