### ISSUE TITLE
create backend for the api

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#5]
Create a solid backend for the app that may server the web form in the website as well

**Comment by elektrolytmangel** [comment]
Probably we can build it with Azure Functions (this is at the moment one of the cheapest and fastest ways to build something like this).

**Comment by chnuessli** [comment]
I have signed up for Azure today, i will take a look at it

**Comment by elektrolytmangel** [comment]
What do you think about this idea? And what is the priority for this task? If we would create a backend, then we can aöways control how the request would be forwarded to OSM even if the app has not been updated on the phone. 
To build the backend, as I already mentioned, I would use Azure Functions based on.Net / c#.

**Comment by chnuessli** [comment]
Sounds good. I've been playing woth frontend lately. Completely new to c# and .NET. The priority to this task is not very high. We can do it if time allows it...

**Comment by chnuessli** [comment]
done by @elektrolytmangel
