### ISSUE TITLE
Create environments for PROD and STAGING

### ISSUE THREAD

**Issue by elektrolytmangel** [chnuessli/defikarte.ch-app#50]
Add variables in app for the backend-url, dependent on dev or production, 
Add variables in function app for the osm-url, user and pwd, staging and production
Add variable for google_api_key in app.json

**Comment by elektrolytmangel** [comment]
google_api_key configured
backend_url configured

@chnuessli can you provide an osm user for the prodction environment? User and password are required.

**Comment by chnuessli** [comment]
OSM User Account created, sent by DM

**Comment by elektrolytmangel** [comment]
added deployment settings on azure function for prod-osm-API
