### ISSUE TITLE
"about" or "project" page

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#57]

**Comment by elektrolytmangel** [comment]
Add an about page, remove the "location" button in the middle, put the "plus" button there. At the right side, put a menu / about button, to show this.
Add the "location" button to the map.

**Comment by elektrolytmangel** [comment]
@chnuessli please checkout the about screen, and tell me hat is missing or what do you want to show there. (At least a german version of the text is needed)

**Comment by chnuessli** [comment]
I transldated your text in german and made some additions to the screen. should be ok for now. https://github.com/chnuessli/defikarte.ch-app/commit/6e22bdc62a1233239328b113c67c60d072a37f87
