### ISSUE TITLE
OSM Tile Overlay (Apple Maps and Google Maps)

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#74]
Since we changed to the OSM Tile layer, the Apple Maps Logo is still visual, can we change that? I dont want to have copyright troubles with apple :)

**Comment by chnuessli** [comment]
![image](https://user-images.githubusercontent.com/63254403/107183214-a95c8080-69de-11eb-870c-2972b936f896.png)

**Comment by elektrolytmangel** [comment]
We still have apple maps data in behind and use the apple-maps engine to display all the stuff. So the logo should be fine (and as I saw in the api documentation, we cannot hide it). But we have to think, to add probably a OSM notice?

**Comment by chnuessli** [comment]
But isn't that a problem when the background map have other coordinates and visuals then the frontend map? Is it difficult to implement the whole map to a plain osm map?
And for an untrained user, the visual sight still implies that he is using apple maps but he isn't?

**Comment by elektrolytmangel** [comment]
It does not have another coordiante system, it has other styling / visuals. Also the data is not only from OSM (see https://en.wikipedia.org/wiki/Apple_Maps#Features). 
We have to use another library, i.e. Mapbox GL for react-native (https://github.com/react-native-mapbox-gl/maps). But at the moment there is no support for expo managed workflow (what we use right now). We have then to eject from that to the "bare workflow". This changes how we build and deploy the application. It is a bigger step, and not so easy to do. There is a feature request, that expos managed workflow supports this library, but it is not on planned yet (https://expo.canny.io/feature-requests/p/add-mapbox-gl-support). 
I think we should consider for the next release to eject from the mangaged workflow and try to switch the maps-framework. For know I would either keep the map as we have it on the main-branch (without osm) or use the overlay as it is right now on the dev-branch.

**Comment by elektrolytmangel** [comment]
Idea: What if we add a button (same as the location-button on the map) to toggle the OSM-overlay? By default it is turned off, if the user wants to have OSM data, he can turn it on. Then we do not have "wrong" Labels on the map and we do have OSM data optionally available.
@chnuessli  what do you think about this solution? Then we have some time, to implement OSM data in a better way, probably as described above.

**Comment by chnuessli** [comment]
Yes, sounds like a good idea to me, so that's a user decision which map he wants to use. so we dont have any copyright complaints.

**Comment by elektrolytmangel** [comment]
The button is now there. For the moment this works.
