### ISSUE TITLE
Backup way to show the defis when overpass is down

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#82]
Every now and then, the overpass api have some hickup's or like today, is for many hours down. We need to get a second way to show the defi's from an other instance. My preferred option would be the geojson files i generate in the other repo (defi_archive). We should also be able to show defis even offline.

**Comment by chnuessli** [comment]
https://github.com/chnuessli/defi_archive/issues/5 die Webkarte nun kurzfristig auf die Main Overpass-Api umgestellt

**Comment by elektrolytmangel** [comment]
At the moment we already have a backup. Beacause our backend caches the osm data, and the app does not directly query the overpass api, there should be always data available, probably old. I will check that this process works fine. So we do not have to build cache functionallity into the app. @chnuessli does this work for you? Or do you want that the app itself is offline (the map layers should then also be cached, but this needs much memory)?

**Comment by chnuessli** [comment]
Yesterday, ther was no data shown in the app, also today (right now) thwe data is not shown in the app. The API has still some issues. I wrote the technical manager of the API, to adress the issue. But the backup way seems not to work right now.

**Comment by elektrolytmangel** [comment]
This should work. @chnuessli please verify, if the next time overpass is down.

**Comment by chnuessli** [comment]
I hope there is no next time

**Comment by elektrolytmangel** [comment]
Does not work at the moment, after testing. Try to fix issues, but need some more logging.

**Comment by elektrolytmangel** [comment]
It works now, after monitoring the service 24h.

**Comment by elektrolytmangel** [comment]
Problem: The singleton-instance of the "SimpleCache" is not function independent. Use instead durable-functions / entities: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp

**Comment by elektrolytmangel** [comment]
Added durable functions. But on server, this uses something about 2s to make the hole request. Probably use AzureCosmosDB Serverless if this is faster: https://devblogs.microsoft.com/cosmosdb/serverless-preview/

**Comment by elektrolytmangel** [comment]
It works, did not got problems in the last weeks. Close the issue. Create new if NoSQL integration is needed.
