### ISSUE TITLE
Expand to Huawei App store

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#97]
Plant ihr auch eine App für Huawei? Denke solche Informationen wären da auch sehr gut zu platzieren.

**Comment by elektrolytmangel** [comment]
https://forums.expo.io/t/publishing-to-huawei-appgallery/38939/3
It is needed to eject from expos "managed workflow" to do this. there is also some native development needed. Best is, if an expirienced developer who knows huawei would do this (if available).

**Comment by chnuessli** [comment]
not a real requirement anymore. we support the two major stores.
